### ISSUE TITLE
PLugin cannot install : crash

### ISSUE THREAD

**Issue by TedMurvol** [Steinerd/Loupedeck.WeatherPlugin#3] opened 2023-02-23 08:29 UTC
**Version**

Loupdeck v 5.4.1.15259 FRENCH
**Submitting a...**

[ X] Bug report
[ ] Feature request

**Current behavior:**

PLugin is installing to Loupedeck, but right after installation, there is a popup saying
"Wetahezr Plugin installation correct. The plugin is ready to use"
But under this popup another popup :
"OUPS!
An error has occured, The plugin has been deactivated because he crashed. To correct it, reactivate or reinstall the plugin."
THere is a button 'Activate thje plugin', but when in click on it, it says 'loupedeck must be restarted and then it stays on 'restarting....' forever.
I must restart or kill the process manually.
When reopen, your plugin does not appear under the plugins management list.

**Expected behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by TedMurvol** [comment] 2023-02-23 08:29
Thanks for your help !

**Comment by steinerd** [comment] 2024-01-10 05:00
Closing, duplicate of #5; addressing changes/updates there.

**Closed as not planned by steinerd** 2024-01-10 05:00 UTC
