### ISSUE TITLE
Also crashes in install

### ISSUE THREAD

**Issue by maillme** [Steinerd/Loupedeck.WeatherPlugin#4] opened 2023-11-23 16:47 UTC
**Submitting a...**

[ x] Bug report
[ ] Feature request

**Current behavior:**
Can't install. Hangs on same screen for installing - crashes whole software. 
Tried several times. 

On OSX, Sanoma, Louoe Deck 
Software of loupdeck, 5.8.1.18
Loupdeck: Live S

<img width="533" alt="Screenshot 2023-11-23 at 17 45 12" src="https://github.com/steinerd/Loupedeck.WeatherPlugin/assets/127260863/cdb630c9-7d1d-4d68-bdaa-541559d3c408">

**Comment by steinerd** [comment] 2024-01-10 04:58
Closing, problem is a duplicate of #5 (didn't see this one until after I already replied to #5)

**Closed as not planned by steinerd** 2024-01-10 04:58 UTC
